# Generated by Django 6.0 on 2025-12-29 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aparelho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('DESKTOP', 'Desktop'), ('IMPRESSORA', 'Impressora'), ('MONITOR', 'Monitor'), ('OUTRO', 'Outro')], max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('cliente', models.CharField(max_length=150)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('MANUTENCAO', 'Manutenção'), ('TROCA', 'Troca de Peça')], max_length=20)),
                ('descricao', models.TextField()),
                ('peca_trocada', models.CharField(blank=True, max_length=150, null=True)),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('aparelho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.aparelho')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario')),
            ],
        ),
    ]
